---
- name: Setup VM
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install basic packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - unzip
        - python3
        - python3-pip
