services:
  backend:
    build: .
    image: myapp-backend:latest
    container_name: myapp-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build: .
    image: myapp-frontend:latest
    container_name: myapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  mysql:
    image: mysql:5.7
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
