project_id           = "your-project-id"
region               = "us-central1"
zone                 = "us-central1-a"
ssh_user             = "your-ssh-username"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"
ssh_private_key_path = "~/.ssh/id_rsa"
db_password          = "your-db-password"
