apiVersion: v1
kind: Secret
metadata:
  name: nicesecret
type: Opaque
data:
  nginx.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRRGVkeCtmeFZlekRGUXoKKzk4V0VRc05XbnRNL2U2bHpZYWpSdDFWVlliWDBnT3Q4MmRKYms2eTY1Rk9ZRTIrWVBQRnlnK2xsSDR4d0NWWApEb2NWNlkzbjZnSnpkTDM4QVZ1Um5mZmlmV1BzbWg5aXVoYXJBSS92dUZCNnZheTFJeGd3WlFBMnRxNTBtZ2ZwCmU5cXNERFJMQ0x6cERINEN6L3dOc0R4c3VueTVuSHhuN3dTaDlGbEZTcHViVm5sdldQL2tPWkdNSEZVN2pHMFIKdWYxSWRmWUw1Q01GWmMxWmtna3Y1aUtmT200NW9Ea1Y0RzVTV0xNNXNRTWpKQy9yYks1QzQzcmp2Tmw0M1BacwoxdElEd25CTnEwMHV6WUMvanAydUR0VlBhNmhoUE55MnQrc0p6QWl3dFpMc1BrQWg0Qzl2akVMa0hHMk5JVHIvCncxM0lVN2ZpM2xuMktZd0Evb3NqSWpTWWFlNVVJci8vNDluc29tcURlNFQrM05oMytOZ1lXcCtWeWFlUXNJVmYKRDlUOW50SVdOSWxYU0Ercms2cXpWdkhBYkFoZ3dYeE9ob1BWSVlDZXJoYW1CZVlFNUprbitRdkNtWWVaREtnMwpCdzkrSGxDeXZMdFlEZTVSc25HdDRNR1hSWFh0cXduNjFKV3B0Z0JxYUhJVTZpNDBsZVFiVFVhYlBqMVE2WUdwCm9sU0w1OW1TcnQ5U1c1cFlkMytwYWZRRE5tRnZZRjdUNk9LVThsdVMraWM1ckYxSXM4S21SRjN4MzRCSzIvTnUKelBjQXZDejVsajgzTG40cTZHUTJDS0E0Z1B4Y1VkZ2lmNyt3Q25uMFhmczZ5N3I5eVlENURqUVJtMC9FMUlydAp5Zm5iRHRrRTl1eWk2eHBLS0txT0dQdHJzb0VKTFFJREFRQUJBb0lDQUJ0QVJHTng3UmhGdmxyUDA3Z0VSbkpRClR5SlRTTlNPcEp1RHBzRTVSTmRUSnBnOFpMNmVBSTN5UlU1d2haVjRrdVA3cUljRDlhRnFoQ2h4NHlKUUJjNE8KNEZYOFN2bC93UlBKWWdBZ2xBajdxRFNUendzTGVwWkc0YlRuWHl5aEsrbGh0ZkQ5MThqNHhWZFlrS1RhcWQwMwpLTXp6ZHN3cFpoclhKOCs1MkdWMFFka0pjbXZVWHNzYUpJMld2akZobVpiL1psRGZkNkZmeGt5UmwvRTBZZnQ2CjZyOVNoU0Vmdm5oYm5Jb2N3anZVNEtsSllMbzltMWJKMURTTnprRHNnencyV1d0a1NzOS9ZY0JiWUVhTm51d2sKdThPcjhNV0dWdEpuaHNHLzBsUjIvQ0oxelJqYUlZWmo5NmR3eUxKZG4vSHVJSk9JMS9LZHkzaGhHaS9iOFg1aQpkNk5mYlkvcm9yTUVYQXptMW5mZ1QrV0ZhQXFwU0ZrUGlRSGM4ejgvSEdyQm5LMkd3UUVtck1EMnR3RWlqeXBvCnM5SUtEa0EzV2FWaHdFZWI2ZmhqRGhKczBoVHJ4LzdyVHBOUzhJeC9ZeFg2TDFnRUlsSndWOHA4NFJFb0sxeXIKdGloQmVnYlcybjN0MExNdUNzRHYvQmp1S2k5N3VCQ2g4eW93cjNBWGNxL1MxQjJpMjFUSzFYQ05aWDZ3K2VGNwo1MWEreWZKTkU3UnJDY1NFRGdZb3k4d3ViNHBKUUlYYm0xNm5Pb1ZYL0k0S21uclpHUVREeWF6ZEpZc0FUbm8wCjlwZWpzQVdBc0ZzK2lteHRnTStHZ08xaVVHbTBBc1orN09QSVRRNU9ZeVJUSm1LNHJrMlZ0cTRGSUpoY3N4YWQKekVGYm9sZDVUUDI4eHZIbWoxS0JBb0lCQVFEblRnS1hvTkJOT3ovY3dTdlhqNDNlSXExOEJuNUZVQkE0R1ZsNwpXRkllM2FTRTVyN0NOd2g5clhMR1ZuY1VRRmlFcUFBMlBmUFRiOVlJUlNIWDJyYnhjc1lRYW5LajhhS2I4RHJnCi9sSEw5TnRrVjQ1bGJabzlVcmF0WVVCU2pLekZGQmJXNnAwZXNCRE5ZYjNTVVJZS0Vac2hxQ1hNZGtENllGMDIKaXlFajV1VVdTbDdUSko0ZFMwM2ErNXlwcStkRko2NzI5Y0phNGlaMkk3VExPb2oxbGZOQ1F1bkl5a2lPNzJJMApTWjhEcTkwaExUdGx0ZXNRMXFxYjM2K2UvQ3RpZkFDejQ5UDRYUkduaFFBLzNmc0NvUTlUSlZXa2tLTG9pdkpqCnJpWm9zaG5GMmR1Si8zc3ZRK3pqN28zTzhGRVI3TmhZUjBiWTJnazNwRWZubkNPVkFvSUJBUUQyTjRRZU1xUVgKSk5GUTlkOEYwNGJwclJTQUk0aFhwbTNvNjBoVTl3V0JWdDZJVUtmNjI4Nis5czF2b2o3T2F3KzFTei9zTG9FYgpYeEQ4V1dsQldJTUE4SHhBWWdqamNkRDY0ejNRZC9zSjI5NTJMUzZibWJqVFdEZWZtQndWRjZ2eHNoa01GV3pkCkwwamhhc21Mc3ptQXFvbDI0Tlc5clBrRjNVbmlBN3lkNkErbE1ZbmdTWkFJdXFhd2s5eUtrSktjVkhIVm9pREwKTEJHWTdRVWxDMGNqN2hlT0pHM0lxakVvdVR5SlFsUkdTVndiSTBYOHFpdmFkL0pHc3N6SU1WenoxUzI3aWRqawpYSHBDRHNDY2lQdHFmMFlYb0htaW5KUWRjanpDMTNEWHhQYk9sSEdKa0YvM2luempCdXJkVTk2WXdoVVJmcG5XCkhSVDFtWUtFVVdrNUFvSUJBUUNKZllsMDhCWmhraEtIK2h0QmF3ZDlQMGU0TFhQcFo0bjhqclR0NkxZSHV1QU0KVDh5Y1RYSXlvbU5UR2hwMll6azZ3VkkrNjl4L2xqNjNjOENHT20vOFhhajJJUkE3KzJvWkgxY2dYb3ZvbkllOAp3WDdYTTZzM1FHOXQ2QnovOUxiTi92OEVpVGtVQUx3OEdSbG9adUtlNFpCQkZWNUNoeGhndTk4c2lNOE9ORFdBClpueXZMVmovT0wveXB4V2NsWjVITVN1RGlOb2FnOHN3OWxDRmJTbjBNVW9EM1JweVRDdU5LeVpJeG1wTEdHRzkKVXRHM3g4Y09uMHVTbEFna2pPaU5CZ0MwN1h3V2Fkd1FvN0plUkdqc1N5aDgxL2hzZGIwZ1ZWZDNnUkU3c29JMwpaU1JtaHdLR09lNGFIcmNVaHl6cFpzdkN6YnVETXplL1oxdUdoUDF4QW9JQkFDVVAzRUpUYXlIVXQvRlE0VjVXCkplTzgydTRpNng0T2ZsTG1QOEFTWXZEQ0s4TW5LUEg0N2xrT2U0UUhUeDd4UEs4VWdhM0Nua3FKZDl3VWRXU1IKdHo2SDlKd1laYkFlN004bkw2SFd2YUlSUjU1UVZNaTFUZjM2TkgxQWYxR3BlNGRwUUozeUI2NFB0US9CYkU4cwpEa2JRNU5wUkk3dG1jeUd2MnJRN3pjT1RMKyswMGtWQnJYMnk0dTZIZzFZVVJ3MWpKTE44c1NVRUlDMzkxNTFvCjRpK0ZZbVJTRlhoMExld3NYZkZuVzVvczVzRnJBTmowb0o5RkdPSU5mZ2ZRYm1hQnUxMlVkV0tDalNDdWFjM20KVExvT0tIWGNBUk02TUkxeUtiVkdpc1RmOENyT2EzekNqNytLU0J4QWFWQWhsTXMzdzhZYllYcTZhL0pBUmtZMgpudmtDZ2dFQkFJSGgzczZXTEEyRzRMclVlbDBNcHdxNlMxWlRxaDBDTEVRQTJWRXpmOG5nNFAyd3VXVm5aMzI1CkRvTUVyZ2pCLy91R2xTdGdzeUx3NXoxSDJGSlhrb2VZZDJOeUNibVp5RExrTkkwMGM5elhtQ2NFMFZWc1NFNzkKTkVpMzBiekg5dXVyMHVHMzBCY0JHMURTQkdBcWdHUUpQN211RFpiY0xpVy9CZnZvTE5wRFUrem5MbXZEM0ZNVQpTL2ZNeWJveWRrVzdyUEJyWFNHUEhyZkdmeVhtdHZYNTE0RzI1RmlDTktPSDNNdTYydit1VFRSL0MySUxSOTFHCmRCMTV0VG90cnJubDh6YWpaZ2dHMG0wZU9xcDV3ajd4MXFKMnFVaTNHVlAyWlcza0t2NG9hRTBxVUxOTlRLTS8KMS9DUE5aQWFBaGxpUXdWdm9rN0JkOWhaQ3BzRXJrWT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  nginx.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhekNDQTFPZ0F3SUJBZ0lVUm8zWUR1NFNlSkRoK1lIYU55Y3E5OG9BUU1Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TXpFeU1Ua3hNVFV3TWpCYUZ3MHpNekV5Ck1UWXhNVFV3TWpCYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnZ0lpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRRGVkeCtmeFZlekRGUXorOThXRVFzTldudE0vZTZsellhalJ0MVZWWWJYCjBnT3Q4MmRKYms2eTY1Rk9ZRTIrWVBQRnlnK2xsSDR4d0NWWERvY1Y2WTNuNmdKemRMMzhBVnVSbmZmaWZXUHMKbWg5aXVoYXJBSS92dUZCNnZheTFJeGd3WlFBMnRxNTBtZ2ZwZTlxc0REUkxDTHpwREg0Q3ovd05zRHhzdW55NQpuSHhuN3dTaDlGbEZTcHViVm5sdldQL2tPWkdNSEZVN2pHMFJ1ZjFJZGZZTDVDTUZaYzFaa2drdjVpS2ZPbTQ1Cm9Ea1Y0RzVTV0xNNXNRTWpKQy9yYks1QzQzcmp2Tmw0M1BaczF0SUR3bkJOcTAwdXpZQy9qcDJ1RHRWUGE2aGgKUE55MnQrc0p6QWl3dFpMc1BrQWg0Qzl2akVMa0hHMk5JVHIvdzEzSVU3ZmkzbG4yS1l3QS9vc2pJalNZYWU1VQpJci8vNDluc29tcURlNFQrM05oMytOZ1lXcCtWeWFlUXNJVmZEOVQ5bnRJV05JbFhTQStyazZxelZ2SEFiQWhnCndYeE9ob1BWSVlDZXJoYW1CZVlFNUprbitRdkNtWWVaREtnM0J3OStIbEN5dkx0WURlNVJzbkd0NE1HWFJYWHQKcXduNjFKV3B0Z0JxYUhJVTZpNDBsZVFiVFVhYlBqMVE2WUdwb2xTTDU5bVNydDlTVzVwWWQzK3BhZlFETm1GdgpZRjdUNk9LVThsdVMraWM1ckYxSXM4S21SRjN4MzRCSzIvTnV6UGNBdkN6NWxqODNMbjRxNkdRMkNLQTRnUHhjClVkZ2lmNyt3Q25uMFhmczZ5N3I5eVlENURqUVJtMC9FMUlydHlmbmJEdGtFOXV5aTZ4cEtLS3FPR1B0cnNvRUoKTFFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVTlSazd1elRyNXhjTGZwUjQ2aXZtUjR6YVBHY3dId1lEVlIwagpCQmd3Rm9BVTlSazd1elRyNXhjTGZwUjQ2aXZtUjR6YVBHY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBZ0VBWnVURmxOTzZYWHFUbFQ5K2NZbXVlSExsSnlVNXZuWVIxVmMvQm9kTU5KNUkKL1BGQ1N1N05CVU5PZGVNMTB2b2N3c2ptREIxZTVqdmsxcUZlbWl6bWdjQnVvVlBSOTZrZHdNYjYrbUV4OENWMQowdkVyeGtmWFk4QllYdW1RK2lncnpFby9ic1ZPRDI2dDFMZEw1TnhHSXQ5cjZNdUtPUlkxcVJwYW1vR1l1U3IzCitpcElyK25KNC9NeXVGcCtmQytENHc2UXdXeUlUcC85b3JNSVlCZXloYWtXRU42SUhVd3o1dXZoVThoRHVZQ2sKMVVTSXFXMVpNMEtjc2VRcTRUajdDMDRqVnZpeGVBMktwamYvejlQU2dmeE90YVRZdGg5V3hZejZSV0x0MUU5cgpOZjh4REwwVFZBSVZva25yRlZhTWV4Smt0SDFIbzQzQThtYVZLVjl0aXFtUnhPemdCNFZOYVdUS1hxTHMycmVwClkwTHlLa3d3alZ4eCt1OW1BZWdoMEI1bFBITFZjU0VGOTJJbjhpSHZmNXNYQU9nVHBvMEFndmpnT3BSVWhGTTEKdHFCaXlycHlSczl4VFBHb0lqMkxabVBpeUF4WHVrTm91M1hJUGJrRW5OdlREa1kvb0owbVF0d29YWlNhQnpEdApnLzZlTFFjRFNkRHRzS2NodUJvSkV3SXNkdWJjZzNsdDJoS05Pa1Y4MjNGQ1MxdEk0L2NobmNQU1VTK3lwRVF6ClJwMGxoMU1CZE9kQjcwemp1MnI1eVRrbjJyNTBTSVE0V013eC9HVlg4R1JwRDBwdktudXZmZktMNllRNmVyTzkKaXN3ZDRMRmZSV1JlV0RkNkpYWUdidjh6elRxYzlSVE41dlpjMG9xRjlJODB0K2ZHUUJlUlcvaGhGV2FjOGdBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: niceconfigmap
data:
  ssl.conf: |
    server {
      listen              443 ssl;
      server_name         localhost;
      ssl_certificate     /etc/nginx/ssl/nginx.crt;
      ssl_certificate_key /etc/nginx/ssl/nginx.key;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nicereplicaset-secret
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
            - name: niceconfigmap
              mountPath: /etc/nginx/conf.d/ssl.conf
              subPath: ssl.conf
              readOnly: true
            - mountPath: /etc/nginx/ssl
              name: nginx-ssl
              readOnly: true
      volumes:
        - name: niceconfigmap
          configMap:
            name: niceconfigmap
        - name: nginx-ssl
          secret:
            secretName: nicesecret
